const data = {
  products: [
    {
      _id: "1",
      name: "Red Oval Socket",
      category: "Sockets",
      image: "/images/s1a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Brown Socket",
      category: "Sockets",
      image: "/images/s2a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Silver Socket",
      category: "Sockets",
      image: "/images/s3a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Silver Brown Socket",
      category: "Sockets",
      image: "/images/s4a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Sky Blue Socket",
      category: "Sockets",
      image: "/images/s5a.png",
      price: 0,
      countInStock: 19,
      brand: "xyz",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Wave Socket",
      category: "Sockets",
      image: "/images/s6a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "Temple Brown Socket",
      category: "Sockets",
      image: "/images/s7a.png",
      price: 0,
      countInStock: 0,
      brand: "xyz",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "8",
      name: "Triangle Brown Socket",
      category: "Sockets",
      image: "/images/s8a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "9",
      name: "Double Ring Socket",
      category: "Sockets",
      image: "/images/s9a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "10",
      name: "Temple Silver Socket",
      category: "Sockets",
      image: "/images/s10a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "11",
      name: "Orange Shiny Socket",
      category: "Sockets",
      image: "/images/s11a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "12",
      name: "Red Tier Socket",
      category: "Sockets",
      image: "/images/s12a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "13",
      name: "Grey Tier Socket",
      category: "Sockets",
      image: "/images/s13a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "14",
      name: "Sky Blue Tier Socket",
      category: "Sockets",
      image: "/images/s14a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "15",
      name: "Orange Tier Socket",
      category: "Sockets",
      image: "/images/s15a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "16",
      name: "Lavender Tier Socket",
      category: "Sockets",
      image: "/images/s16a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "17",
      name: "Brown Tier Socket",
      category: "Sockets",
      image: "/images/s17a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "18",
      name: "Pink Triangle Socket",
      category: "Sockets",
      image: "/images/s18a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "19",
      name: "Pink Half-Bubble Socket",
      category: "Sockets",
      image: "/images/s19a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "20",
      name: "Pink Oval Socket",
      category: "Sockets",
      image: "/images/s20a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "21",
      name: "Pink Hexagonal Socket",
      category: "Sockets",
      image: "/images/s21a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "22",
      name: "Brown Double-face Temple Socket",
      category: "Sockets",
      image: "/images/s22a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "23",
      name: "Brown Bell Shaped Socket",
      category: "Sockets",
      image: "/images/s23a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "24",
      name: "Brown Sliding Socket",
      category: "Sockets",
      image: "/images/s24a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      _id: "25",
      name: "Silver Brown flat bell Socket",
      category: "Sockets",
      image: "/images/s25a.png",
      price: 0,
      countInStock: 6,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
  ],
};
export default data;
