import bcrypt from "bcryptjs";
const data = {
  users: [
    {
      name: "Surabhi Plywood",
      email: "admin@exampple.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "shivani",
      email: "user@exampple.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Red Oval Socket",
      category: "Sockets",
      image: "/images/s1a.png",
      price: 100,
      countInStock: 0,
      brand: "xyz",
      rating: 4.5,
      numReviews: 16,
      description: "low quality product",
    },
    {
      name: "Brown Socket",
      category: "Sockets",
      image: "/images/s2a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Silver Socket",
      category: "Sockets",
      image: "/images/s3a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Silver Brown Socket",
      category: "Sockets",
      image: "/images/s4a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 3.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Sky Blue Socket",
      category: "Sockets",
      image: "/images/s5a.png",
      price: 0,
      countInStock: 19,
      brand: "xyz",
      rating: 5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Wave Socket",
      category: "Sockets",
      image: "/images/s6a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Temple Brown Socket",
      category: "Sockets",
      image: "/images/s7a.png",
      price: 0,
      countInStock: 0,
      brand: "xyz",
      rating: 2,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Triangle Brown Socket",
      category: "Sockets",
      image: "/images/s8a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Double Ring Socket",
      category: "Sockets",
      image: "/images/s9a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Temple Silver Socket",
      category: "Sockets",
      image: "/images/s10a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Orange Shiny Socket",
      category: "Sockets",
      image: "/images/s11a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Red Tier Socket",
      category: "Sockets",
      image: "/images/s12a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Grey Tier Socket",
      category: "Sockets",
      image: "/images/s13a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Sky Blue Tier Socket",
      category: "Sockets",
      image: "/images/s14a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Orange Tier Socket",
      category: "Sockets",
      image: "/images/s15a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Lavender Tier Socket",
      category: "Sockets",
      image: "/images/s16a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Brown Tier Socket",
      category: "Sockets",
      image: "/images/s17a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Pink Triangle Socket",
      category: "Sockets",
      image: "/images/s18a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Pink Half-Bubble Socket",
      category: "Sockets",
      image: "/images/s19a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Pink Oval Socket",
      category: "Sockets",
      image: "/images/s20a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Pink Hexagonal Socket",
      category: "Sockets",
      image: "/images/s21a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Brown Double-face Temple Socket",
      category: "Sockets",
      image: "/images/s22a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Brown Bell Shaped Socket",
      category: "Sockets",
      image: "/images/s23a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Brown Sliding Socket",
      category: "Sockets",
      image: "/images/s24a.png",
      price: 0,
      countInStock: 10,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Silver Brown flat bell Socket",
      category: "Sockets",
      image: "/images/s25a.png",
      price: 0,
      countInStock: 7,
      brand: "xyz",
      rating: 4.5,
      numReviews: 17,
      description: "high quality product",
    },
  ],
};
export default data;
