const data = {
  products: [
    {
      _id: "1",
      name: "Red Oval Socket",
      category: "Sockets",
      image: "/images/s1a.jpg",
      price: 0,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "2",
      name: "Brown Socket",
      category: "Sockets",
      image: "/images/s2a.jpg",
      price: 0,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "4",
      name: "Silver Brown Socket",
      category: "Sockets",
      image: "/images/s4a.png",
      price: 0,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "5",
      name: "Sky Blue Socket",
      category: "Sockets",
      image: "/images/s5a.jpg",
      price: 0,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "6",
      name: "Wave Socket",
      category: "Sockets",
      image: "/images/s6a.jpg",
      price: 0,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "7",
      name: "Temple Brown Socket",
      category: "Sockets",
      image: "/images/s7a.jpg",
      price: 0,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
    {
      _id: "3",
      name: "Silver Socket",
      category: "Sockets",
      image: "/images/s3a.jpg",
      price: 0,
      brand: "xyz",
      rating: 4,
      numReviews: 10,
      description: "high quality product",
    },
  ],
};
export default data;
